weights: ''
cfg: models/v5Lite-e-Pconv.yaml
data: data/mydata.yaml
hyp: data/hyp.scratch.yaml
epochs: 2400
batch_size: 128
img_size:
- 320
- 320
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: '0'
multi_scale: true
single_cls: true
adam: true
sync_bn: false
local_rank: -1
workers: 12
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/exp4
total_batch_size: 128
