weights: runs/train/exp7/weights/last.pt
cfg: models/v5Lite-e-Ghost.yaml
data: data/mydata.yaml
hyp: data/hyp.scratch.yaml
epochs: 4000
batch_size: 24
img_size:
- 320
- 320
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: 0
workers: 12
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 2
global_rank: 0
save_dir: runs/train/exp8
total_batch_size: 48
